[package]
name = "daytask"
version = "0.1.0"
edition = "2024"
rust-version = "1.85.1"
description = "todo"
repository = "https://github.com/uselessstar/daytask"
license = "ISC"

[lib]
bench = false
doc = true
doctest = true
name = "daytask"
path = "src/lib.rs"
test = true

[dependencies]
log = { version = "0.4.34", optional = true }
serde = { version = "1.0.229", features = ["derive"], optional = true }
thiserror = "2.0.20"
uuid = { version = "1.26.1", features = ["v7"] }

[dev-dependencies]
serde_json = "1.0.151"

[features]
default = ["log", "v7"]
log = ["dep:log"]
serde = ["dep:serde", "log/serde", "uuid/serde"]
v4 = ["uuid/v4"]
v7 = ["uuid/v7"]

[lints.clippy]
allow_attributes = "deny"
allow_attributes_without_reason = "warn"
complexity = { level = "warn", priority = -1 }
correctness = { level = "deny", priority = -1 }
manual_non_exhaustive = "warn"
missing_errors_doc = "warn"
missing_panics_doc = "warn"
missing_safety_doc = "warn"
perf = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }
too_many_lines = "warn"
use_self = "warn"

[lints.rust]
irrefutable_let_patterns = "warn"
missing_copy_implementations = "warn"
missing_debug_implementations = "deny"
missing_docs = "warn"
unused = { level = "warn", priority = -1 }
warnings = "warn"
