[package]
name = "daytask"
version = "0.0.0"
edition = "2024"
description = "todo"
repository = "https://github.com/uselessstar/daytask"
license = "ISC"

[lib]
bench = false
doc = true
doctest = true
name = "daytask"
path = "src/lib.rs"
test = true

[lints.clippy]
allow_attributes = "deny"
allow_attributes_without_reason = "warn"
correctness = { level = "forbid", priority = -1 }

[lints.rust]
missing_copy_implementations = "warn"
missing_debug_implementations = "deny"
missing_docs = "warn"
unused = { level = "warn", priority = -1 }
warnings = "warn"
